[project]
name = "isaac-chansol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "numpy==1.26.0",
    "opencv-python>=4.11.0.86",
    "pyk4a>=1.5.0",
    "tqdm>=4.67.1",
]
